import GenericEmail from "@workspace/transactional/emails/generic";
import { tool } from "ai";
import { Resend } from "resend";
import { z } from "zod";

// Input schema for sending an email reply
const sendEmailReplySchema = z.object({
  to: z.email().describe("Recipient email address"),
  subject: z
    .string()
    .describe("Original email subject (will be prefixed with Re: if needed)"),
  content: z.string().describe("The reply content in markdown format"),
  from: z
    .email()
    .describe("Sender email address (must be verified domain in Resend)"),
  headers: z.object({
    messageId: z
      .string()
      .nullable()
      .optional()
      .describe("Original message ID for threading"),
    references: z
      .array(z.string())
      .optional()
      .describe("Reference headers for email threading"),
  }),
});

type SendEmailToolInput = z.infer<typeof sendEmailReplySchema>;

const DEFAULT_FOOTER =
  "This message is generated by an AI assistant. It may not reflect the views of the recipient. Please verify any information before acting upon it. If you want to learn more, visit [https://somai.me/os](https://somai.me/os).";

// Server-side tool that requires confirmation (no execute function)
export const sendEmailTool = (env: Env) =>
  tool({
    description:
      "Send an email reply with proper threading headers. Use this to respond to incoming emails.",
    inputSchema: sendEmailReplySchema,
    async execute(input: SendEmailToolInput) {
      try {
        const resend = new Resend(env.RESEND_API_KEY);

        const subject = input.subject.startsWith("Re:")
          ? input.subject
          : `Re: ${input.subject}`;

        const { data, error } = await resend.emails.send({
          from: input.from,
          to: input.to,
          subject,
          react: (
            <GenericEmail content={input.content} footer={DEFAULT_FOOTER} />
          ),
          headers: {
            "In-Reply-To": input.headers?.messageId || "",
            References: input.headers?.references?.join(" ") || "",
          },
        });

        if (error) {
          console.error("Resend error:", error);
          return { id: null, error: error.message };
        }

        if (!data) {
          return { id: null, error: "No data returned from Resend" };
        }

        console.log("Email sent via Resend:", data.id);
        return { id: data.id, error: null };
      } catch (err) {
        console.error("Failed to send email via Resend:", err);
        return {
          id: null,
          error: err instanceof Error ? err.message : String(err),
        };
      }
    },
  });
