import GenericEmail from "@workspace/transactional/emails/generic";
import { CreateEmailOptions, Resend } from "resend";
import { Message } from "@/agent/types";

const DEFAULT_FOOTER =
  "This message is generated by an AI assistant. It may not reflect the views of the recipient. Please verify any information before acting upon it. If you want to learn more, visit [https://somai.me/os](https://somai.me/os).";

/**
 * EmailTool - Email sending via Resend API
 * Bypasses Cloudflare email operation limits by using external HTTP API
 */
export class EmailTool {
  private apiKey: string;
  private resend: Resend;

  constructor(apiKey: string) {
    this.apiKey = apiKey;
    this.resend = new Resend(this.apiKey);
  }

  /**
   * Send an email via Resend API
   * @param from - Sender email address (must be verified domain in Resend)
   * @param to - Recipient email address
   * @param subject - Email subject
   * @param html - HTML content
   * @param text - Plain text content (optional)
   * @param replyTo - Reply-To address (optional)
   * @param inReplyTo - In-Reply-To header for threading (optional)
   * @param references - References header for threading (optional)
   */
  private async sendEmail(
    params: CreateEmailOptions
  ): Promise<{ id: string; error: null } | { id: null; error: Error }> {
    try {
      const { data, error } = await this.resend.emails.send(params);

      if (error) {
        console.error("Resend error:", error);
        return { id: null, error: new Error(error.message) };
      }

      if (!data) {
        return {
          id: null,
          error: new Error("No data returned from Resend"),
        };
      }

      console.log("Email sent via Resend:", data.id);
      return { id: data.id, error: null };
    } catch (error) {
      console.error("Failed to send email via Resend:", error);
      return {
        id: null,
        error: error instanceof Error ? error : new Error(String(error)),
      };
    }
  }

  /**
   * Send a reply email with proper threading headers
   * Extracts subject and creates proper In-Reply-To/References headers
   */
  async sendReply(
    message: Message,
    content: string,
    from: string
  ): Promise<{ id: string; error: null } | { id: null; error: Error }> {
    return this.sendEmail({
      from: from,
      to: message.from,
      subject: message.subject.startsWith("Re:")
        ? message.subject
        : `Re: ${message.subject}`,
      react: <GenericEmail content={content} footer={DEFAULT_FOOTER} />,
      headers: {
        "In-Reply-To": message.messageId || "",
        References: message.references?.join(" ") || "",
      },
    });
  }
}
