/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EssaysRouteImport } from './routes/essays'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EssaySlugRouteImport } from './routes/essay/$slug'
import { Route as EssayChar123slugChar125DotmdRouteImport } from './routes/essay/{$slug}[.]md'
import { Route as EssaySlugMdRouteImport } from './routes/essay/$slug.md'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysRoute = EssaysRouteImport.update({
  id: '/essays',
  path: '/essays',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaySlugRoute = EssaySlugRouteImport.update({
  id: '/essay/$slug',
  path: '/essay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EssayChar123slugChar125DotmdRoute =
  EssayChar123slugChar125DotmdRouteImport.update({
    id: '/essay/{$slug}.md',
    path: '/essay/{$slug}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const EssaySlugMdRoute = EssaySlugMdRouteImport.update({
  id: '/md',
  path: '/md',
  getParentRoute: () => EssaySlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/essays': typeof EssaysRoute
  '/papers': typeof PapersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/essay/$slug': typeof EssaySlugRouteWithChildren
  '/essay/{$slug}.md': typeof EssayChar123slugChar125DotmdRoute
  '/essay/$slug/md': typeof EssaySlugMdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/essays': typeof EssaysRoute
  '/papers': typeof PapersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/essay/$slug': typeof EssaySlugRouteWithChildren
  '/essay/{$slug}.md': typeof EssayChar123slugChar125DotmdRoute
  '/essay/$slug/md': typeof EssaySlugMdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/essays': typeof EssaysRoute
  '/papers': typeof PapersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/essay/$slug': typeof EssaySlugRouteWithChildren
  '/essay/{$slug}.md': typeof EssayChar123slugChar125DotmdRoute
  '/essay/$slug/md': typeof EssaySlugMdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/essays'
    | '/papers'
    | '/sitemap.xml'
    | '/essay/$slug'
    | '/essay/{$slug}.md'
    | '/essay/$slug/md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/essays'
    | '/papers'
    | '/sitemap.xml'
    | '/essay/$slug'
    | '/essay/{$slug}.md'
    | '/essay/$slug/md'
  id:
    | '__root__'
    | '/'
    | '/essays'
    | '/papers'
    | '/sitemap.xml'
    | '/essay/$slug'
    | '/essay/{$slug}.md'
    | '/essay/$slug/md'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EssaysRoute: typeof EssaysRoute
  PapersRoute: typeof PapersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EssaySlugRoute: typeof EssaySlugRouteWithChildren
  EssayChar123slugChar125DotmdRoute: typeof EssayChar123slugChar125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays': {
      id: '/essays'
      path: '/essays'
      fullPath: '/essays'
      preLoaderRoute: typeof EssaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay/$slug': {
      id: '/essay/$slug'
      path: '/essay/$slug'
      fullPath: '/essay/$slug'
      preLoaderRoute: typeof EssaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay/{$slug}.md': {
      id: '/essay/{$slug}.md'
      path: '/essay/{$slug}.md'
      fullPath: '/essay/{$slug}.md'
      preLoaderRoute: typeof EssayChar123slugChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay/$slug/md': {
      id: '/essay/$slug/md'
      path: '/md'
      fullPath: '/essay/$slug/md'
      preLoaderRoute: typeof EssaySlugMdRouteImport
      parentRoute: typeof EssaySlugRoute
    }
  }
}

interface EssaySlugRouteChildren {
  EssaySlugMdRoute: typeof EssaySlugMdRoute
}

const EssaySlugRouteChildren: EssaySlugRouteChildren = {
  EssaySlugMdRoute: EssaySlugMdRoute,
}

const EssaySlugRouteWithChildren = EssaySlugRoute._addFileChildren(
  EssaySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EssaysRoute: EssaysRoute,
  PapersRoute: PapersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EssaySlugRoute: EssaySlugRouteWithChildren,
  EssayChar123slugChar125DotmdRoute: EssayChar123slugChar125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
