/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as EssaysRouteImport } from './routes/essays'
import { Route as BabyRouteImport } from './routes/baby'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OgPapersDotpngRouteImport } from './routes/og.papers[.]png'
import { Route as OgHomeDotpngRouteImport } from './routes/og.home[.]png'
import { Route as OgEssaysDotpngRouteImport } from './routes/og.essays[.]png'
import { Route as EssaySlugDotmdRouteImport } from './routes/essay.$slug[.]md'
import { Route as EssaySlugRouteImport } from './routes/essay.$slug'
import { Route as OgEssaySlugDotpngRouteImport } from './routes/og.essay.$slug[.]png'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysRoute = EssaysRouteImport.update({
  id: '/essays',
  path: '/essays',
  getParentRoute: () => rootRouteImport,
} as any)
const BabyRoute = BabyRouteImport.update({
  id: '/baby',
  path: '/baby',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgPapersDotpngRoute = OgPapersDotpngRouteImport.update({
  id: '/og/papers.png',
  path: '/og/papers.png',
  getParentRoute: () => rootRouteImport,
} as any)
const OgHomeDotpngRoute = OgHomeDotpngRouteImport.update({
  id: '/og/home.png',
  path: '/og/home.png',
  getParentRoute: () => rootRouteImport,
} as any)
const OgEssaysDotpngRoute = OgEssaysDotpngRouteImport.update({
  id: '/og/essays.png',
  path: '/og/essays.png',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaySlugDotmdRoute = EssaySlugDotmdRouteImport.update({
  id: '/essay/$slug.md',
  path: '/essay/$slug.md',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaySlugRoute = EssaySlugRouteImport.update({
  id: '/essay/$slug',
  path: '/essay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgEssaySlugDotpngRoute = OgEssaySlugDotpngRouteImport.update({
  id: '/og/essay/$slug.png',
  path: '/og/essay/$slug.png',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baby': typeof BabyRoute
  '/essays': typeof EssaysRoute
  '/papers': typeof PapersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/essay/$slug': typeof EssaySlugRoute
  '/essay/$slug.md': typeof EssaySlugDotmdRoute
  '/og/essays.png': typeof OgEssaysDotpngRoute
  '/og/home.png': typeof OgHomeDotpngRoute
  '/og/papers.png': typeof OgPapersDotpngRoute
  '/og/essay/$slug.png': typeof OgEssaySlugDotpngRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baby': typeof BabyRoute
  '/essays': typeof EssaysRoute
  '/papers': typeof PapersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/essay/$slug': typeof EssaySlugRoute
  '/essay/$slug.md': typeof EssaySlugDotmdRoute
  '/og/essays.png': typeof OgEssaysDotpngRoute
  '/og/home.png': typeof OgHomeDotpngRoute
  '/og/papers.png': typeof OgPapersDotpngRoute
  '/og/essay/$slug.png': typeof OgEssaySlugDotpngRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baby': typeof BabyRoute
  '/essays': typeof EssaysRoute
  '/papers': typeof PapersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/essay/$slug': typeof EssaySlugRoute
  '/essay/$slug.md': typeof EssaySlugDotmdRoute
  '/og/essays.png': typeof OgEssaysDotpngRoute
  '/og/home.png': typeof OgHomeDotpngRoute
  '/og/papers.png': typeof OgPapersDotpngRoute
  '/og/essay/$slug.png': typeof OgEssaySlugDotpngRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baby'
    | '/essays'
    | '/papers'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/essay/$slug'
    | '/essay/$slug.md'
    | '/og/essays.png'
    | '/og/home.png'
    | '/og/papers.png'
    | '/og/essay/$slug.png'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baby'
    | '/essays'
    | '/papers'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/essay/$slug'
    | '/essay/$slug.md'
    | '/og/essays.png'
    | '/og/home.png'
    | '/og/papers.png'
    | '/og/essay/$slug.png'
  id:
    | '__root__'
    | '/'
    | '/baby'
    | '/essays'
    | '/papers'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/essay/$slug'
    | '/essay/$slug.md'
    | '/og/essays.png'
    | '/og/home.png'
    | '/og/papers.png'
    | '/og/essay/$slug.png'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BabyRoute: typeof BabyRoute
  EssaysRoute: typeof EssaysRoute
  PapersRoute: typeof PapersRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EssaySlugRoute: typeof EssaySlugRoute
  EssaySlugDotmdRoute: typeof EssaySlugDotmdRoute
  OgEssaysDotpngRoute: typeof OgEssaysDotpngRoute
  OgHomeDotpngRoute: typeof OgHomeDotpngRoute
  OgPapersDotpngRoute: typeof OgPapersDotpngRoute
  OgEssaySlugDotpngRoute: typeof OgEssaySlugDotpngRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays': {
      id: '/essays'
      path: '/essays'
      fullPath: '/essays'
      preLoaderRoute: typeof EssaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baby': {
      id: '/baby'
      path: '/baby'
      fullPath: '/baby'
      preLoaderRoute: typeof BabyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/papers.png': {
      id: '/og/papers.png'
      path: '/og/papers.png'
      fullPath: '/og/papers.png'
      preLoaderRoute: typeof OgPapersDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/home.png': {
      id: '/og/home.png'
      path: '/og/home.png'
      fullPath: '/og/home.png'
      preLoaderRoute: typeof OgHomeDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/essays.png': {
      id: '/og/essays.png'
      path: '/og/essays.png'
      fullPath: '/og/essays.png'
      preLoaderRoute: typeof OgEssaysDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay/$slug.md': {
      id: '/essay/$slug.md'
      path: '/essay/$slug.md'
      fullPath: '/essay/$slug.md'
      preLoaderRoute: typeof EssaySlugDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay/$slug': {
      id: '/essay/$slug'
      path: '/essay/$slug'
      fullPath: '/essay/$slug'
      preLoaderRoute: typeof EssaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/essay/$slug.png': {
      id: '/og/essay/$slug.png'
      path: '/og/essay/$slug.png'
      fullPath: '/og/essay/$slug.png'
      preLoaderRoute: typeof OgEssaySlugDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BabyRoute: BabyRoute,
  EssaysRoute: EssaysRoute,
  PapersRoute: PapersRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EssaySlugRoute: EssaySlugRoute,
  EssaySlugDotmdRoute: EssaySlugDotmdRoute,
  OgEssaysDotpngRoute: OgEssaysDotpngRoute,
  OgHomeDotpngRoute: OgHomeDotpngRoute,
  OgPapersDotpngRoute: OgPapersDotpngRoute,
  OgEssaySlugDotpngRoute: OgEssaySlugDotpngRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
